title: Biothermica
description: Integrated carbon and energy project developer
lang: en
baseurl: ""
url: ""

defaults:
  - scope:
      path: "en"
    values:
      layout: default
      lang: en

  - scope:
      path: "fr"
    values:
      layout: default
      lang: fr

exclude:
  - node
  - taxonomy
  - modules
